/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#20005f",
        "on-primary-fixed-variant": "#4f00d0",
        "on-tertiary-fixed": "#320046",
        "outline": "#948ea1",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "inverse-surface": "#e4e0f2",
        "outline-variant": "#494455",
        "surface-container-high": "#2a2836",
        "tertiary-fixed-dim": "#edb1ff",
        "surface-container-highest": "#353341",
        "tertiary-container": "#9e51bc",
        "surface-container-lowest": "#0e0d19",
        "secondary-fixed-dim": "#e9c349",
        "secondary": "#e9c349",
        "tertiary": "#edb1ff",
        "on-secondary": "#3c2f00",
        "secondary-fixed": "#ffe088",
        "on-error": "#690005",
        "surface": "#13121e",
        "surface-container-low": "#1b1a27",
        "secondary-container": "#af8d11",
        "surface-container": "#1f1e2b",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#cdbdff",
        "on-primary-container": "#fcf6ff",
        "on-secondary-fixed-variant": "#574500",
        "surface-variant": "#353341",
        "on-tertiary": "#520070",
        "surface-bright": "#393845",
        "inverse-primary": "#6833ea",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#6e208c",
        "on-primary": "#370096",
        "on-surface-variant": "#cac3d8",
        "background": "#13121e",
        "primary-fixed": "#e8deff",
        "surface-dim": "#13121e",
        "on-surface": "#e4e0f2",
        "tertiary-fixed": "#f9d8ff",
        "on-secondary-container": "#342800",
        "inverse-on-surface": "#302f3c",
        "primary-container": "#7c4dff",
        "primary": "#cdbdff",
        "on-tertiary-container": "#fff6fc",
        "on-background": "#e4e0f2",
        "surface-tint": "#cdbdff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
